spring:
  servlet:
    multipart:
#     配置单个文件最大上传大小
      max-file-size: 10MB
#     配置单个请求最大上传大小（一次请求可以上传多个文件）
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.springframework.jdbc.support JdbcTransactionManager: debug

# 对象/Map集合
user:
  name: zhangsan
  age: 18
  password: 123456

# 数组/List/Set集合
hobby:
  - java
  - game
  - sport

