logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /testhost
    username: testall
#    virtual-host: /
#    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: none
        retry:
          #开启消费者失败重试机制
          enabled: true
          #失败后的初始等待时间
          initial-interval: 1000ms
          #失败后下次的等待时长倍数， 下次等待时长=interval*multiplier
          multiplier: 1
          #最大重试次数
          max-attempts: 3
          stateless: true #true无状态，false有状态，如果业务中包含事物，这里改为false
    #设置MQ的连接超时时间
    connection-timeout: 1s
    template:
      retry:
        #开启超时重试机制
        enabled: true
        #失败后的初始等待时间
        initial-interval: 1000ms
        #失败后下次的等待时长倍数， 下次等待时长=interval*multiplier
        multiplier: 1
        #最大重试次数
        max-attempts: 3
    #开启publisher confirm机制并设置confirm类型
    publisher-confirm-type: correlated
    #开启publisher returns机制
    publisher-returns: true